FROM eclipse-temurin:18-jre-alpine as builder
WORKDIR app
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} sample_spring_boot_api.jar
## Extracts the layers of the JAR
RUN java -Djarmode=layertools -jar sample_spring_boot_api.jar extract

FROM eclipse-temurin:18-jre-alpine
WORKDIR app
## Copy over JAR layers from builder
COPY --from=builder app/dependencies/ ./
COPY --from=builder app/spring-boot-loader/ ./
COPY --from=builder app/snapshot-dependencies/ ./
COPY --from=builder app/application/ ./
ENTRYPOINT [ "java", "org.springframework.boot.loader.JarLauncher" ]




